title: Mayank Raj
description: "Documenting has never been my priority, but I feel the need for it..."
show_downloads: true
author: "Mayank Raj"

permalink: "/:title/"
baseurl: ""

url_github_project: "asas https://github.com/rajmayank/personal-website"
url_github_profile: "https://github.com/rajmayank"
url_linkedin: "https://github.com/rajmayank"
url_facebook: "https://www.facebook.com/mayank9856"
email: "mayank9856@gmail.com"

google_analytics: "UA-89686348-1"
cayman-blog:
  date_format: "%b %-d, %Y"

theme:

