baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Mayank Raj"


googleAnalytics = "UA-89686348-1"
enableRobotsTXT = true

[author]
    name = "Mayank Raj"

# [params]
#     author = "Mayank Raj"
#     title = "Senior Software Engineer"
#     dateformat = "Jan 1, 2001"


disableKinds = ["taxonomy", "taxonomyTerm"]
[taxonomies]


# TODO: look into 'generator' key in the feed
[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"