export const showcases = [
  {
    type: "image",
    link: "",
    thumbnail: "/showcase/360p/CactusTech_Interview2.png",
    title: "Interview @ CactusTech",
    subtitle: "An Associate Director talks opportunities",
    banner: "Media Publication",
  },
  {
    type: "video",
    link: "",
    thumbnail: "/showcase/360p/OSI_2023_Timelapse.png",
    title: "Open Source India",
    subtitle: "GitOps Mastery",
    banner: "Conference",
  },
  {
    type: "video",
    link: "",
    thumbnail: "/showcase/360p/GIDS_2024_Timelapse.png",
    title: "Developers Summit",
    subtitle: "Resilient Cybersecurity Strategies",
    banner: "Summit",
  },
  {
    type: "image",
    link: "",
    thumbnail: "/showcase/360p/AuthO_Jenkins.png",
    title: "AuthO by Okta",
    subtitle: "CI pipelines",
    banner: "Guest post",
  },
  {
    type: "image",
    link: "",
    thumbnail: "/showcase/360p/DigitalOcean_RXJS.png",
    title: "DigitalOcean",
    subtitle: "Search Bar with RxJS",
    banner: "Guest post",
  },
  {
    type: "image",
    link: "",
    thumbnail: "/showcase/360p/OSFY_Interview.png",
    title: "Open Source For You",
    subtitle: "Open Source Ecosystem",
    banner: "Media Publications",
  },
];
